### ISSUE TITLE
Unable to communicate with Accordance. Can’t make some data into the expected type. (Error -1700)

### ISSUE THREAD

**Issue by kimsg1984** [darinfranklin/RegexForAccordance#2]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
MacOS: Big Sur(11.1)
Accordance: 12.3.7

After installation, I tried to execute and get some message "Unable to communicate with Accordance. Can’t make some data into the expected type. "  with Erro code  -1700.

**Comment by darinfranklin** [comment]
I am unable to reproduce that error. I tried RegexForAccordance 1.0.11 with Accordance 12.3.7 on Big Sur (11.1).  

Does that happen right away when RegexForAccordance starts? It is running a script on startup to get the list of text modules from Accordance.  

Please try this and show me what you get.

1. Open Script Editor.app.

2. Paste the following line into the top section.

```
tell application "Accordance" to «event AccdVerL»
```

3. Script > Run

You should get something like this:
```
{"NRSVS", "NAS95S", "KJVS", "CSB17S", "HMT-W4", "LXX-B", "GNT28-T", "BHS-W4", "GNT-T"}
```

Copy and paste the result here.
