### ISSUE TITLE
Sequence of Hebrew Consonant, Vowel, Accent

### ISSUE THREAD

**Issue by martinmts** [darinfranklin/RegexForAccordance#3]
Hi,
Thanks a lot for sharing this tool. It can do things Accordance cannot do.
I have a question regarding the sequence of Hebrew consonants, vowels, and accents.
What sequence should I follow in search?
For instance, If I copy הַבָּשָׁ֔ן (Deut 1:4) in Accordance and convert the string into character names. It looks like this:
`{Hey}{Pathach}{Beth}{Dagesh or Mappiq}{Qamets}{Shin}{Shin Dot}{Qamets}{Zaqeph Qaton}{Final Nun}`

However, in the search result of RegexForAccordance, the same verb has this:
`{Hey}{Pathach}{Beth}{Qamets}{Dagesh or Mappiq}{Shin}{Qamets}{Shin Dot}{Zaqeph Qaton}{Final Nun}`

As you can see, `Qamets` and `Dagesh` switches place; `Shin Dot` and `Qamets` also switched place.

When we use regex for search, the sequence will become important.
There are also prepositives and postpositives for the accents. Pashta may be written twice if the stress does not fall on ultima. I've been wondering how to handle these issues in searching.

Thanks!

**Comment by darinfranklin** [comment]
The strings go through NSString [decomposedStringWithCanonicalMapping](https://developer.apple.com/documentation/foundation/nsstring/1409474-decomposedstringwithcanonicalmap). The documentation for that says it produces "A string made by normalizing the string’s contents using the Unicode Normalization Form D."

The documentation for [Unicode Normalization Forms](https://www.unicode.org/reports/tr15/) explains what Normalization Form D (NFD) (Canonical Decomposition) means. I have not read it in detail. It looks complicated. 

It might be easier just to try a few examples and see if you can find the pattern. From the few examples I checked, it looks like vowels come first, then dagesh or shin dot, then cantillation.
