### ISSUE TITLE
Universal App

### ISSUE THREAD

**Issue by Berovowilare** [darinfranklin/RegexForAccordance#4]
Hello Darin

Is it planned to release an universal app for the new Apple chips?

Thanks

**Comment by darinfranklin** [comment]
I built [v1.0.12](https://github.com/darinfranklin/RegexForAccordance/releases/tag/v1.0.12) as a Universal app.  Please try this and let me know if it works for you.

**Comment by Berovowilare** [comment]
Hello Darin

I'm still on an Intel Mac, I want to change this as soon as possible. I can say the v1.0.12 works.

Thanks
