### ISSUE TITLE
Glitch in Filters

### ISSUE THREAD

**Issue by Berovowilare** [darinfranklin/RegexForAccordance#5]
Hello Darin

The Remove Greek ... has an issue.

Thanks
<img width="189" alt="Bildschirm­foto 2022-08-19 um 20 49 19" src="https://user-images.githubusercontent.com/36891575/185687525-cec043ff-22a6-4a51-abb6-9a75bf47edf0.png">

V. 1.0.12 (54)

**Comment by darinfranklin** [comment]
This is fixed in [v1.0.13](https://github.com/darinfranklin/RegexForAccordance/releases/tag/v1.0.13).  Thanks for reporting it.
