### ISSUE TITLE
Simple searches with wildcards

### ISSUE THREAD

**Issue by Berovowilare** [darinfranklin/RegexForAccordance#6]
Hello Darin

If I search for "Mose*" I get in my opinion wrong results.
Instead of "Mose" "Moses" etc. it deletes the last character and find other words. Like "Mos" "Most" 

<img width="822" alt="Bildschirmfoto 2023-07-19 um 11 31 48" src="https://github.com/darinfranklin/RegexForAccordance/assets/36891575/85eddb23-3bc9-4e87-bb54-97b44b12cad3">

Maybe I do something wrong.

Thanks

**Comment by darinfranklin** [comment]
In regular expressions, the `*` matches 0 or more of the previous character.  It is not the same as the "wildcard" that Accordance uses.  `Mose*` matches `Mos`, followed by 0 or more `e` characters.  You are finding "Mos" and "Mose", which is correct.

Here is how to find all words that start with "Mose".

`\bMose\w*`

* `\b` matches the beginning of a word, the transition from whitespace to the first letter of the word
* `Mose` matches those literal characters
* `\w` matches any word character, not whitespace
* `*` matches 0 or more of the previous character

This matches the start of a word, then "Mose", then any other characters until it finds whitespace.

In NRSV, I find Moses, Moseroth, and Moserah.

**Comment by Berovowilare** [comment]
Thanks. Got it. 
I see it works a little bit different  than the Grep in BBEdit too. 
But I see it works the same in AntConc https://www.laurenceanthony.net/software.html.

Thanks
